### ISSUE TITLE
Webpack is not getting compiled with node version < 14

### ISSUE THREAD

**Issue by Chetan77verma** [module-federation/fmr#3]
I tried to configure **fmr** on node version > 14 it is working fine 

but i want to make it work on node version 12 but webpack is not getting complied

```
/node_modules/@module-federation/fmr/src/server/sockets/modules/useSocketMessage.js:36
      data: data ?? undefined,
                  ^

SyntaxError: Unexpected token '?'
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (/Users/chetanverma/phable/phable.doctor.frontend.rx/ams-appointment/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/chetanverma/phable/phable.doctor.frontend.rx/ams-appointment/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/Users/chetanverma/phable/phable.doctor.frontend.rx/ams-appointment/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/chetanverma/phable/phable.doctor.frontend.rx/ams-appointment/node_modules/@module-federation/fmr/src/server/sockets/handlers/index.js:4:30)
    at Module._compile (/Users/chetanverma/phable/phable.doctor.frontend.rx/ams-appointment/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

Some code contains es2020 , which is not support by node 12

I tried things but not able resolve it , if you guys know how i can do that it will be great help @ScriptedAlchemy

**Comment by IamDixit** [comment]
Facing the exact same issue, any updates

**Comment by Harveyallen** [comment]
Facing the exact same issue,config the bable-loader that including this node_module but nothing happen.

**Comment by Chetan77verma** [comment]
any update @ScriptedAlchemy @statianzo  ??

**Comment by statianzo** [comment]
@Chetan77verma, sorry, I'm not associated with this fork of `webpack-livereload-plugin`.

**Comment by emphaticsunshine** [comment]
Any update on this?

**Comment by ScriptedAlchemy** [comment]
Anyone wanna send a PR? Looks like we are using too new a syntax?
